### ISSUE TITLE
Radiance to reflectance and other factors

### ISSUE THREAD

**Issue by drnextgis** [stac-extensions/eo#11]
There are some factors per band that we would like to expose through STAC and it seems this extension is a good candidate for that:

* `radiance_to_reflectance` (radiance to reflectance)
* `dn_to_radiance` (digital number to radiance)
* `dn_to_toa` (digital number to top of atmosphere reflectance)

I'd like to hear your input. Thanks!

**Comment by emmanuelmathot** [comment]
Optical calibration and more specifically conversion from DN to TOA reflectance need the following parameters that are already included in this extension and some others:

- day and month of acquisition: core STAC spec
- sun elevation angle: https://github.com/stac-extensions/view#item-properties
- scale and offset, one pair of values for each band: https://github.com/stac-extensions/raster/#raster-band-object
- solar illuminations, one value for each band: https://github.com/stac-extensions/eo#solar_illumination

For the conversion from DN (for Digital Numbers) to spectral radiance (or ‘TOA radiance’) L, the following formula can be used:

    L(b) = DN(b)*scale(b)+offset(b) (in W/m2/steradians/micrometers) with b being a band ID.

In order to convert TOA radiance to TOA reflectance, the following formula can be used:

    R(b) = (pi*L(b)*d*d) / (ESUN(b)*cos(θ)) 

where:
- L(b) is the spectral radiance for band b
- d is the earth-sun distance (in astronomical units) and depends on the acquisition’s day and month
- ESUN(b) is the mean TOA solar irradiance (or solar illumination) in W/m2/micrometers
- θ is the solar zenith angle in degrees.

see https://www.orfeo-toolbox.org/CookBook/Applications/app_OpticalCalibration.html

**Comment by drnextgis** [comment]
Thank you @emmanuelmathot for your detailed answer! I believe it will be useful for others with similar question.

**Comment by cholmes** [comment]
+1 - could be good to include that info directly in the scale and offset section of raster band. It looks like the first is there, but I don't see TOA radiance to TOA reflectance.
